# -*- coding: utf-8 -*-
"""Drug_Deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fw0LrtmGPkBlGl-In6LTdgnG9WfY2LL-
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
import pickle

# Load dataset
df = pd.read_csv("drug200.csv")

# Encode categorical data
le = LabelEncoder()
for col in ['Sex', 'BP', 'Cholesterol', 'Drug']:
    df[col] = le.fit_transform(df[col])

# Split data
X = df.drop('Drug', axis=1)
y = df['Drug']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Train model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Save model
pickle.dump(model, open('Drug Prediction Model.pkl', 'wb'))
